### ISSUE TITLE
Rogue, Stomper

### ISSUE THREAD

**Issue by malaang** [KitPvPDE/kitpvp-issues#9]
Wenn ein Rogue einen Stomper auf dem Tower deaktiviert und der Stomper runterspringt, dann bekommt der Stomper trotzdem weniger Fallschaden.
Wenn ein Stomper vom Tower runterspringt und unten ein Rogue steht, der das Kit deaktiviert, bekommt der Stomper ebenfalls weniger Fallschaden.

**Comment by fleonce** [comment]
Fixed in https://github.com/KitPvPDE/kitpvp-plugin/commit/125c25fc6d48b795ce0d302c133ecfb6f41ad2ec
